<a href="https://colab.research.google.com/github/Alina1-10/NM/blob/main/%D0%9B%D1%80_4_%D0%93%D1%83%D0%B1%D0%BD%D0%B8%D1%86%D1%8C%D0%BA%D0%B0_%D0%90%D0%BB%D1%96%D0%BD%D0%B0_7_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

була присутня на парі

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [2]:
matrix = np.random.randint(1, 6, size=(3, 3))

matrix

array([[2, 5, 1],
       [4, 1, 5],
       [4, 2, 1]])

In [3]:
det = np.linalg.det(matrix)
det

np.float64(65.99999999999997)

In [4]:
product = np.prod(matrix)
product

np.int64(1600)

In [5]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(1600)

In [6]:
sum_1 = np.sum(matrix)

sum_1

np.int64(25)

In [7]:
np.max(matrix)

np.int64(5)

In [8]:
np.min(matrix)


np.int64(1)

In [10]:
max_element = np.max(matrix)

print("Найбільний елемент:", max_element)

min_element = np.min(matrix)

print("Найменший елемент:", min_element)

Найбільний елемент: 5
Найменший елемент: 1


In [14]:
mean = np.mean(matrix)
print("Середнє:", mean)

Середнє: 2.7777777777777777


In [19]:
sqrt_matrix = np.sqrt(matrix)
print(sqrt_matrix)

[[1.41421356 2.23606798 1.        ]
 [2.         1.         2.23606798]
 [2.         1.41421356 1.        ]]


In [21]:
row_sums = np.sum(matrix, axis=1).reshape(-1,1)
print(row_sums)

[[ 8]
 [10]
 [ 7]]


In [22]:
vector = np.random.randint(0, 10, size=25)
print(vector)

sorted_vector = np.sort(vector)[::-1]

print(sorted_vector)

[1 8 9 9 8 5 0 3 9 7 4 0 9 1 3 9 2 9 4 5 9 3 6 8 3]
[9 9 9 9 9 9 9 8 8 8 7 6 5 5 4 4 3 3 3 3 2 1 1 0 0]


In [24]:
a = np.array([[3, -5, 3], [1, 2, 1], [2, 7, -1]])
b = np.array([1, 4, 8])

x = np.linalg.solve(a, b)
print('Вбудована функція', x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1)

Вбудована функція [1. 1. 1.]
Матричний метод [1. 1. 1.]


In [25]:
# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        #print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions
# Виклик функцій для розв'язання системи
print(kramer(a, b))

Solving a system of linear algebraic equations by Cramer's method:
[np.float64(1.0), np.float64(1.0), np.float64(1.0)]
